name: Deploy Eleventy site to GitHub Pages

on:
  push:
    branches: [ master ]  # or main, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: production-files
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Eleventy
        run: npx @11ty/eleventy

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Checkout repo (needed for deploy)
        uses: actions/checkout@v4

      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # optional: specify folder explicitly if needed
          folder: _site
